server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/identity/** #only exposes needed endpoints.
          filters:
            - StripPrefix=2 #this will skip the /api/v1 as 2 prefixes and call to http://localhost:8080/identity/**
        - id: profile_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2

services:
  urls:
    identity_service:
      http://localhost:8080/identity